### ISSUE TITLE
productname incorrect for G8 and G9 servers

### ISSUE THREAD

**Issue by jeffNagra** [logicminds/hpilo#3]
FYI, the productname fact for G8 and G9 servers is incorrect, They need to be Gen8/Gen9..

    # Not all ilos have the same feature set and thus ilo configs are not backwards compatible
    case $productname {
      /G5/: { $ilogen = 2 }
      /G6/: { $ilogen = 2 }
      /G4/: { $ilogen = 1 }
      /G3/: { $ilogen = 0 }
      /G7/: { $ilogen = 3 }
      /Gen8/: { $ilogen = 4 }
      /Gen9/: { $ilogen = 4 }
      default: { $ilogen = 1 }
    }

**Comment by logicminds** [comment]
Thanks.  I had to guess since g6 was the last version I used.  Do you know if the template still applies?

**Comment by logicminds** [comment]
fixed in latest.
